sudo: required
language: generic

services:
  - docker

before_install:
   - docker build -t traning2/react-test-f ./client/Dockerfile.dev ./client

script:
   - docker build -e CI=true traning2/react-test npm test

after_success:
   - docker build -t traning2/multi-client ./client
   - docker build -t traning2/multi-nginx ./nginx
   - docker build -t traning2/multi-server ./server
   - docker build -t traning2/multi-worker ./worker
   
